colors

diff --git a/utils/nbtest b/utils/nbtest
--- a/utils/nbtest
+++ b/utils/nbtest
@@ -50,6 +50,10 @@ python3 -m jupyter kernelspec list
 
 JULIA_VERSION=$(julia --version | cut --delimiter=' ' --field=3);
 JULIA_VERSION_XY=$(echo $JULIA_VERSION | cut  --delimiter='.' --field=1,2);
+NFAILS=0
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m' # No Color
 
 echo JULIA_VERSION $JULIA_VERSION $JULIA_VERSION_XY
 
@@ -58,4 +62,14 @@ for i in "${notebooks[@]}"; do
    sed --regexp-extended --in-place "s/julia-1.[0-9]/julia-$JULIA_VERSION_XY/g" "$i";
    sed --regexp-extended --in-place "s/Julia 1.[0-9].[0-9]/Julia $JULIA_VERSION/g" "$i";
    python3 -m nbconvert --to html --execute --ExecutePreprocessor.timeout=360 "$i";
+   if [ "$?" != "0" ]; then
+       echo -e "${RED}$FILE failed${NC}"
+       let NFAILS=NFAILS+1
+   else
+       echo -e "${GREEN}$FILE OK${NC}"
+   fi
 done
+
+if [ $NFAILS != "0" ]; then
+    exit 1
+fi
